### ISSUE TITLE
New Error :

### ISSUE THREAD

**Issue by PenguinsLords** [espiroaka/stw-dupe#1]
TypeError: Cannot read properties of undefined (reading '1')
    at C:\Users\Bar\Desktop\Dupe\javascript\index.js:124:106
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Bar\Desktop\Dupe\javascript\index.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by espiroaka** [comment]
With the improvement of messages that should no longer appear
